## Test project and lift using numpy by creating a trivial orthogoal projector

In [8]:
import numpy as np

In [9]:
## define projector
data_dim = 4
num_data = 3
red_dim = 2

A = np.arange(0, data_dim * data_dim, 1).reshape(data_dim, data_dim) 

print('A.shape: {}'.format(A.shape))
print('a')
for i in range(a.shape[0]):
    print(a[i])

print('\nA')
for i in range(A.shape[0]):
    print(A[i,:])

# orthogonalize A
A, _ = np.linalg.qr(A.T)

print('\nA')
for i in range(A.shape[0]):
    print(A[i,:])

# create a projector from A (reduced dimension is 2)
A = A[:, :red_dim].T

print('\nProjector A.shape: ', A.shape)
for i in range(A.shape[0]):
    print(A[i,:])

A.shape: (4, 4)
a
[[0]
 [1]
 [2]
 [3]]
[[4]
 [5]
 [6]
 [7]]
[[ 8]
 [ 9]
 [10]
 [11]]

A
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]

A
[ 0.         -0.83666003  0.54251529  0.07534696]
[-0.26726124 -0.47809144 -0.77951402  0.3039044 ]
[-0.53452248 -0.11952286 -0.06851781 -0.83384969]
[-0.80178373  0.23904572  0.30551655  0.45459833]

Projector A.shape:  (2, 4)
[ 0.         -0.26726124 -0.53452248 -0.80178373]
[-0.83666003 -0.47809144 -0.11952286  0.23904572]


In [10]:
a = np.arange(0, data_dim*num_data, 1).reshape(num_data, data_dim)
print('a.shape: {}'.format(a.shape))

# project (both methods work)
print('\nProject test')
for i in range(a.shape[0]):
    # a1_proj = np.dot(A, a[i,:]) 
    a1_proj = np.dot(a[i,:], A.T) 
    print('\na{}_proj.shape: {}'.format(i+1, a1_proj.shape))
    for j in range(a1_proj.shape[0]):
        print(a1_proj[j])

# a_batch_proj = np.dot(A, a.T).T 
a_batch_proj = np.dot(a, A.T) 
print('\n\na_batch_proj.shape: {}'.format(a_batch_proj.shape))
for i in range(a_batch_proj.shape[0]):
    print(a_batch_proj[i,:])

a.shape: (3, 4)

Project test

a1_proj.shape: (2,)
-3.7416573867739413
-5.551115123125783e-16

a2_proj.shape: (2,)
-10.155927192672127
-4.780914437337577

a3_proj.shape: (2,)
-16.57019699857031
-9.561828874675154


a_batch_proj.shape: (3, 2)
[-3.74165739e+00 -5.55111512e-16]
[-10.15592719  -4.78091444]
[-16.570197    -9.56182887]


In [ ]:
# lift (both methods work)
print('Lift test')
b = a_batch_proj # data in reduced dimension

for i in range(b.shape[0]):
    # b1_lift = np.dot(A.T, b[i,:]) 
    b1_lift = np.dot(b[i,:], A)
    print('\nb{}_lift.shape: {}'.format(i+1, b1_lift.shape))
    for j in range(b1_lift.shape[0]):
        print(b1_lift[j])

# b_batch_lift = np.dot(A.T, b.T).T 
b_batch_lift = np.dot(b, A)
print('\n\nb_batch_lift.shape: {}'.format(b_batch_lift.shape))
for i in range(b_batch_lift.shape[0]):
    print(b_batch_lift[i,:])

Lift test

b1_lift.shape: (4,)
4.644396126208126e-16
1.0000000000000002
2.0
3.0

b2_lift.shape: (4,)
4.0000000000000036
5.000000000000002
6.000000000000002
7.000000000000001

b3_lift.shape: (4,)
8.000000000000007
9.000000000000004
10.000000000000004
11.000000000000002


b_batch_lift.shape: (3, 4)
[4.64439613e-16 1.00000000e+00 2.00000000e+00 3.00000000e+00]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [12]:
x = a[i, :]
print('x.shape: {}'.format(x.shape))

x_proj = np.dot(x, A.T)
print('x_proj.shape: {}'.format(x_proj.shape))

x.shape: (4,)
x_proj.shape: (2,)


## Testing projectors with data with additional dimensions

### Adding additional dimension at the end

In [24]:
a = np.arange(0, data_dim*num_data, 1).reshape(num_data, data_dim, 1)
print('a.shape: {}'.format(a.shape))

# project 
print('\nProject and lift test')
for i in range(a.shape[0]):
    print('\na[{}].shape = {}, a[{}] = {}'.format(i, a[i].shape, i, a[i].flatten()))
    
    # project
    a1_proj = np.dot(A, a[i])
    print('\na1_proj.shape = {}, a1_proj = {}'.format(a1_proj.shape, a1_proj.flatten()))

    # lift
    a1_lift = np.dot(A.T, a1_proj)
    print('\na1_lift.shape = {}, a1_lift = {}'.format(a1_lift.shape, a1_lift.flatten()))

# batch projectb_batch_lift = np.dot(b, A)
a_batch_proj = np.dot(A, a.T).T
a_batch_proj = a_batch_proj.reshape(-1, red_dim, 1)
print('\n\na_batch_proj.shape: {}'.format(a_batch_proj.shape))

for i in range(a_batch_proj.shape[0]):
    print('a_batch_proj[{}].shape = {}, a_batch_proj[{}] = {}'.format(i, a_batch_proj[i].shape, i, a_batch_proj[i].flatten()))


# batch lift
b_batch_lift = np.dot(A.T, a_batch_proj)
b_batch_lift = b_batch_lift[:, :, 0].T
b_batch_lift = b_batch_lift.reshape(-1, data_dim, 1)
# b_batch_lift = np.dot(a_batch_proj, A)
print('\n\nb_batch_lift.shape: {}'.format(b_batch_lift.shape))
for i in range(b_batch_lift.shape[0]):
    print('b_batch_lift[{}].shape = {}, b_batch_lift[{}] = {}'.format(i, b_batch_lift[i].shape, i, b_batch_lift[i].flatten()))

a.shape: (3, 4, 1)

Project and lift test

a[0].shape = (4, 1), a[0] = [0 1 2 3]

a1_proj.shape = (2, 1), a1_proj = [-3.74165739e+00 -5.55111512e-16]

a1_lift.shape = (4, 1), a1_lift = [4.64439613e-16 1.00000000e+00 2.00000000e+00 3.00000000e+00]

a[1].shape = (4, 1), a[1] = [4 5 6 7]

a1_proj.shape = (2, 1), a1_proj = [-10.15592719  -4.78091444]

a1_lift.shape = (4, 1), a1_lift = [4. 5. 6. 7.]

a[2].shape = (4, 1), a[2] = [ 8  9 10 11]

a1_proj.shape = (2, 1), a1_proj = [-16.570197    -9.56182887]

a1_lift.shape = (4, 1), a1_lift = [ 8.  9. 10. 11.]


a_batch_proj.shape: (3, 2, 1)
a_batch_proj[0].shape = (2, 1), a_batch_proj[0] = [-3.74165739e+00 -5.55111512e-16]
a_batch_proj[1].shape = (2, 1), a_batch_proj[1] = [-10.15592719  -4.78091444]
a_batch_proj[2].shape = (2, 1), a_batch_proj[2] = [-16.570197    -9.56182887]


b_batch_lift.shape: (3, 4, 1)
b_batch_lift[0].shape = (4, 1), b_batch_lift[0] = [4.64439613e-16 1.00000000e+00 2.00000000e+00 3.00000000e+00]
b_batch_lift[1].shape = (4,

In [23]:
## can project and lift on object with less dimension using usual method
a = np.arange(0, data_dim*num_data, 1).reshape(num_data, data_dim, 1)
print('a.shape: {}'.format(a.shape))

# project 
print('\nProject and lift test')
for i in range(a.shape[0]):
    print('\na[{}].shape = {}, a[{}] = {}'.format(i, a[i].shape, i, a[i].flatten()))
    
    # project
    a1_proj = np.dot(a[i,:, 0], A.T)
    a1_proj = a1_proj.reshape(red_dim, 1)
    print('\na1_proj.shape = {}, a1_proj = {}'.format(a1_proj.shape, a1_proj.flatten()))

    # lift
    a1_lift = np.dot(a1_proj[:,0], A)
    a1_lift = a1_lift.reshape(data_dim, 1)
    print('\na1_lift.shape = {}, a1_lift = {}'.format(a1_lift.shape, a1_lift.flatten()))

# batch projectb_batch_lift = np.dot(b, A)
a_batch_proj = np.dot(a[:, :, 0], A.T)
a_batch_proj = a_batch_proj.reshape(a_batch_proj.shape[0], a_batch_proj.shape[1], 1)
print('\n\na_batch_proj.shape: {}'.format(a_batch_proj.shape))

for i in range(a_batch_proj.shape[0]):
    print('a_batch_proj[{}].shape = {}, a_batch_proj[{}] = {}'.format(i, a_batch_proj[i].shape, i, a_batch_proj[i].flatten()))


# batch lift
b_batch_lift = np.dot(a_batch_proj[:, :, 0], A)
b_batch_lift = b_batch_lift.reshape(b_batch_lift.shape[0], b_batch_lift.shape[1], 1)
# b_batch_lift = np.dot(a_batch_proj, A)
print('\n\nb_batch_lift.shape: {}'.format(b_batch_lift.shape))
for i in range(b_batch_lift.shape[0]):
    print('b_batch_lift[{}].shape = {}, b_batch_lift[{}] = {}'.format(i, b_batch_lift[i].shape, i, b_batch_lift[i].flatten()))

a.shape: (3, 4, 1)

Project and lift test

a[0].shape = (4, 1), a[0] = [0 1 2 3]

a1_proj.shape = (2, 1), a1_proj = [-3.74165739e+00 -5.55111512e-16]

a1_lift.shape = (4, 1), a1_lift = [4.64439613e-16 1.00000000e+00 2.00000000e+00 3.00000000e+00]

a[1].shape = (4, 1), a[1] = [4 5 6 7]

a1_proj.shape = (2, 1), a1_proj = [-10.15592719  -4.78091444]

a1_lift.shape = (4, 1), a1_lift = [4. 5. 6. 7.]

a[2].shape = (4, 1), a[2] = [ 8  9 10 11]

a1_proj.shape = (2, 1), a1_proj = [-16.570197    -9.56182887]

a1_lift.shape = (4, 1), a1_lift = [ 8.  9. 10. 11.]


a_batch_proj.shape: (3, 2, 1)
a_batch_proj[0].shape = (2, 1), a_batch_proj[0] = [-3.74165739e+00 -5.55111512e-16]
a_batch_proj[1].shape = (2, 1), a_batch_proj[1] = [-10.15592719  -4.78091444]
a_batch_proj[2].shape = (2, 1), a_batch_proj[2] = [-16.570197    -9.56182887]


b_batch_lift.shape: (3, 4, 1)
b_batch_lift[0].shape = (4, 1), b_batch_lift[0] = [4.64439613e-16 1.00000000e+00 2.00000000e+00 3.00000000e+00]
b_batch_lift[1].shape = (4,

### Adding additional dimension at second last position

In [25]:
a = np.arange(0, data_dim*num_data, 1).reshape(num_data, 1, data_dim)
print('a.shape: {}'.format(a.shape))

## can project and lift on object with less dimension using usual method

# project 
print('\nProject and lift test')
for i in range(a.shape[0]):
    print('\na[{}].shape = {}, a[{}] = {}'.format(i, a[i].shape, i, a[i].flatten()))
    
    # project
    a1_proj = np.dot(a[i, 0, :], A.T)
    a1_proj = a1_proj.reshape(1, red_dim)
    print('\na1_proj.shape = {}, a1_proj = {}'.format(a1_proj.shape, a1_proj.flatten()))

    # lift
    a1_lift = np.dot(a1_proj[0, :], A)
    a1_lift = a1_lift.reshape(1, data_dim)
    print('\na1_lift.shape = {}, a1_lift = {}'.format(a1_lift.shape, a1_lift.flatten()))

# batch projectb_batch_lift = np.dot(b, A)
a_batch_proj = np.dot(a[:, 0, :], A.T)
a_batch_proj = a_batch_proj.reshape(a_batch_proj.shape[0], 1, a_batch_proj.shape[1])
print('\n\na_batch_proj.shape: {}'.format(a_batch_proj.shape))

for i in range(a_batch_proj.shape[0]):
    print('a_batch_proj[{}].shape = {}, a_batch_proj[{}] = {}'.format(i, a_batch_proj[i].shape, i, a_batch_proj[i].flatten()))


# batch lift
b_batch_lift = np.dot(a_batch_proj[:, 0, :], A)
b_batch_lift = b_batch_lift.reshape(b_batch_lift.shape[0], 1, b_batch_lift.shape[1])
# b_batch_lift = np.dot(a_batch_proj, A)
print('\n\nb_batch_lift.shape: {}'.format(b_batch_lift.shape))
for i in range(b_batch_lift.shape[0]):
    print('b_batch_lift[{}].shape = {}, b_batch_lift[{}] = {}'.format(i, b_batch_lift[i].shape, i, b_batch_lift[i].flatten()))

a.shape: (3, 1, 4)

Project and lift test

a[0].shape = (1, 4), a[0] = [0 1 2 3]

a1_proj.shape = (1, 2), a1_proj = [-3.74165739e+00 -5.55111512e-16]

a1_lift.shape = (1, 4), a1_lift = [4.64439613e-16 1.00000000e+00 2.00000000e+00 3.00000000e+00]

a[1].shape = (1, 4), a[1] = [4 5 6 7]

a1_proj.shape = (1, 2), a1_proj = [-10.15592719  -4.78091444]

a1_lift.shape = (1, 4), a1_lift = [4. 5. 6. 7.]

a[2].shape = (1, 4), a[2] = [ 8  9 10 11]

a1_proj.shape = (1, 2), a1_proj = [-16.570197    -9.56182887]

a1_lift.shape = (1, 4), a1_lift = [ 8.  9. 10. 11.]


a_batch_proj.shape: (3, 1, 2)
a_batch_proj[0].shape = (1, 2), a_batch_proj[0] = [-3.74165739e+00 -5.55111512e-16]
a_batch_proj[1].shape = (1, 2), a_batch_proj[1] = [-10.15592719  -4.78091444]
a_batch_proj[2].shape = (1, 2), a_batch_proj[2] = [-16.570197    -9.56182887]


b_batch_lift.shape: (3, 1, 4)
b_batch_lift[0].shape = (1, 4), b_batch_lift[0] = [4.64439613e-16 1.00000000e+00 2.00000000e+00 3.00000000e+00]
b_batch_lift[1].shape = (1,